---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: lab-cluster
  region: us-east-1

nodeGroups:
  - name: spot
    labels: { role: workers }
    tags:
      Name: spot
      k8s.io/cluster-autoscaler/cluster_name: owned
      k8s.io/cluster-autoscaler/enabled: "true"
    minSize: 2
    maxSize: 100
    instancesDistribution:
      instanceTypes: ["m5.large", "m5a.large", "m5n.large", "m4.large"]
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 50
      spotAllocationStrategy: capacity-optimized
    privateNetworking: true
    asgMetricsCollection:
      - granularity: 1Minute
        metrics:
          - GroupMinSize
          - GroupMaxSize
          - GroupDesiredCapacity
          - GroupInServiceInstances
          - GroupPendingInstances
          - GroupStandbyInstances
          - GroupTerminatingInstances
          - GroupTotalInstances
    ssh:
      publicKeyName: "{{ aws_public_keypair_name }}"
    iam:
      instanceProfileARN: "{{ eks_node_aws_iam_instance_profile_arn }}"
      instanceRoleARN: "{{ eks_node_aws_iam_role_arn }}"
    securityGroups:
      attachIDs: ["{{ node_sg_security_group_id }}"]
